version: "3.7"
services:
  app:
    image: countries-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "7050:3000"
